# version: '3.8'

# Define a base configuration to avoid repetition
x-airflow-base: &airflow-base
  build:
    context: .
    dockerfile: Dockerfile
    args:
      # Use the AIRFLOW_UID from the .env file to set the user in the Dockerfile
      - AIRFLOW_UID=${AIRFLOW_UID:-50000}
  # Use the .env with RDS credentials in base folder: financial-etl-poc/.env
  env_file:
    - ../credentials.env
  environment:
    # Construct the database connection string from your .env variables
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${rds_username}:${rds_password}@${rds_host}:${rds_port}/${rds_dbname}
    # Set other core Airflow configurations
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=false
    - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
    - AIRFLOW__WEBSERVER__SECRET_KEY=${WEBSERVER_SECRET_KEY:-your-super-secret-key-change-me} # Add a default secret key
  volumes:
    - ./config:/opt/airflow/config
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins


services:

  # The service that initializes the Airflow database and creates the first user
  airflow-init:
    <<: *airflow-base
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        # Initialize the database
        airflow db init
        # Create the admin user if they don't exist
        airflow users create \
          --username ${AIRFLOW_USERNAME} \
          --password ${AIRFLOW_PASSWORD} \
          --firstname Joe \
          --lastname Lu \
          --role Admin \
          --email Joe.Zhou.Lu@gmail.com || true

  # The Airflow webserver service
  airflow-webserver:
    <<: *airflow-base
    container_name: airflow_webserver
    restart: always
    command: airflow webserver
    ports:
      - "8080:8080"
    depends_on:
      # This ensures the webserver only starts after the database is initialized
      airflow-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # The Airflow scheduler service
  airflow-scheduler:
    <<: *airflow-base
    container_name: airflow_scheduler
    restart: always
    command: airflow scheduler
    depends_on:
      # This ensures the scheduler only starts after the database is initialized
      airflow-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname \"$${HOSTNAME}\""]
      interval: 30s
      timeout: 10s
      retries: 3